/*
 *  ApplicationConstants.h
 *  AppKit
 *
 *  Created by rupert on 4/03/11.
 *  Copyright 2011 2RMobile. All rights reserved.
 *
 */

#define DATABASE_NAME @"appkit.db"

#define TABLEVIEW_CELL_IMAGEVIEW_WIDTH			85.0f //This is fixed
#define TABLEVIEW_CELL_IMAGEVIEW_HEIGHT			65.0f
	
#define PADDING_TOP								 2.0f
#define PADDING_BOTTOM							 2.0f
#define PADDING_LEFT							 2.0f
#define PADDING_RIGHT							 2.0f

#define TABLEVIEW_CELL_THUMB_BACKGROUND_WIDTH		TABLEVIEW_CELL_IMAGEVIEW_WIDTH + PADDING_TOP + PADDING_BOTTOM
#define TABLEVIEW_CELL_THUMB_BACKGROUND_HEIGHT		TABLEVIEW_CELL_IMAGEVIEW_HEIGHT + PADDING_TOP + PADDING_BOTTOM

#define TABLEVIEW_CELL_HEIGHT						TABLEVIEW_CELL_THUMB_BACKGROUND_HEIGHT + PADDING_TOP + PADDING_BOTTOM

#define IMAGECELL_CONTENT_TEXT_WIDTH				320.0f - (TABLEVIEW_CELL_THUMB_BACKGROUND_WIDTH + PADDING_LEFT + PADDING_RIGHT)
#define IMAGECELL_CONTENT_LEFT						PADDING_LEFT + TABLEVIEW_CELL_THUMB_BACKGROUND_WIDTH + PADDING_RIGHT

#define DARK_BACKGROUND  [UIColor colorWithRed:151.0/255.0 green:152.0/255.0 blue:155.0/255.0 alpha:1.0]
#define LIGHT_BACKGROUND [UIColor colorWithRed:172.0/255.0 green:173.0/255.0 blue:175.0/255.0 alpha:1.0]